Select Type, IsHazmat, 
IsActive,
IsCatchWeight, 
ReceiptUpdateOption, 
ReceiptScanOption, 
AutoPrintOnPickOption, 
StackLimit, ShelfLife, 
DefaultLocationCategory, 
QtyPickLocationMinimum, 
RouteOption, 
ComingleOption,
BarCodeScanOption,
Length,
Width,
Height,
Cube,
Weight,
Tare,
SizeSequence,
UnitPrice,
UnitCost,
MinimumStockLevel,
DutyRate,
HazmatFlashPoint,
HazmatBoilingPoint,
HasImages,
LotConsolidationOption,
SecondaryDutyRate